---

- name: install opentelemtry collector
  ansible.builtin.apt:
    deb: https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.42.0/otel-contrib-collector_0.42.0_amd64.deb

- name: restart service
  ansible.builtin.service:
    name: otel-contrib-collector
    state: restarted

...